_wandb:
    value:
        cli_version: 0.22.2
        e:
            i6qesrpqolpw0f1fd89i6dctt2fv1c0a:
                args:
                    - --project
                    - linear-attn-demo
                    - --steps
                    - "2000"
                    - --d
                    - "32"
                    - --tau
                    - "0.5"
                    - --alpha
                    - "0.1"
                    - --variablecontext
                codePath: structured_linear_regression_icl/run.py
                codePathLocal: run.py
                cpu_count: 96
                cpu_count_logical: 96
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "53660876800"
                        used: "19761106944"
                email: maryletey@g.harvard.edu
                executable: /n/home05/mletey/.conda/envs/mytorchenv/bin/python
                git:
                    commit: d8c658e58f0316eb818e5051793ccacf07641c52
                    remote: https://github.com/mletey/icl-bde.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-31e681d0-34a6-f221-a336-56b61416cd7d
                host: holygpu8a11304.rc.fas.harvard.edu
                memory:
                    total: "1622574587904"
                os: Linux-4.18.0-553.44.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /n/holystore01/LABS/pehlevan_lab/Lab/mletey/icl-bde/structured_linear_regression_icl/run.py
                python: CPython 3.10.18
                root: /n/holystore01/LABS/pehlevan_lab/Lab/mletey/icl-bde/structured_linear_regression_icl
                slurm:
                    cluster_name: odyssey
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    cpus_per_gpu: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: kempner_grads
                    job_cpus_per_node: "1"
                    job_end_time: "1760563749"
                    job_gid: "5057"
                    job_gpus: "0"
                    job_id: "41575470"
                    job_name: linear_attn_grid_tau0p5_alpha0p1_vctrue
                    job_nodelist: holygpu8a11304
                    job_num_nodes: "1"
                    job_partition: kempner_h100
                    job_qos: normal
                    job_start_time: "1760560149"
                    job_uid: "64802"
                    job_user: mletey
                    jobid: "41575470"
                    localid: "0"
                    mem_per_gpu: "24576"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: holygpu8a11304
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: holygpu8a11304
                    submit_dir: /n/holystore01/LABS/pehlevan_lab/Lab/mletey/icl-bde/structured_linear_regression_icl
                    submit_host: holylogin08.rc.fas.harvard.edu
                    task_pid: "2496949"
                    tasks_per_node: "1"
                    topology_addr: main.holyoke.holyndr.holygpu8a11304
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2025-10-15T20:29:54.415044Z"
                writerId: i6qesrpqolpw0f1fd89i6dctt2fv1c0a
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
alpha:
    value: 0.1
amp:
    value: false
cpu:
    value: false
ctask:
    value: identity
d:
    value: 32
eval_every:
    value: 100
functionality:
    value: 1
grad_clip:
    value: 1
log_every:
    value: 25
lr:
    value: 0.001
project:
    value: linear-attn-demo
rho:
    value: 0.01
run_name:
    value: ""
seed:
    value: 0
steps:
    value: 2000
tau:
    value: 0.5
variablecontext:
    value: true
weight_decay:
    value: 0
