_wandb:
    value:
        cli_version: 0.22.2
        e:
            e0z4hgxcti04n4dvt59n6th4o14vcamm:
                args:
                    - --project
                    - linear-attn-demo
                    - --steps
                    - "2000"
                    - --d
                    - "32"
                    - --alpha
                    - "1"
                    - --tau
                    - "3"
                codePath: structured_linear_regression_icl/run.py
                codePathLocal: run.py
                cpu_count: 64
                cpu_count_logical: 64
                disk:
                    /:
                        total: "53660876800"
                        used: "19786629120"
                email: maryletey@g.harvard.edu
                executable: /n/home05/mletey/.conda/envs/mytorchenv/bin/python
                git:
                    commit: d8c658e58f0316eb818e5051793ccacf07641c52
                    remote: https://github.com/mletey/icl-bde.git
                host: holygpu8a19301.rc.fas.harvard.edu
                memory:
                    total: "1081297342464"
                os: Linux-4.18.0-553.44.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: /n/holystore01/LABS/pehlevan_lab/Lab/mletey/icl-bde/structured_linear_regression_icl/run.py
                python: CPython 3.10.18
                root: /n/holystore01/LABS/pehlevan_lab/Lab/mletey/icl-bde/structured_linear_regression_icl
                slurm:
                    cluster_name: odyssey
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "1"
                    cpus_per_gpu: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: kempner_pehlevan_lab
                    job_cpus_per_node: "1"
                    job_end_time: "1760502605"
                    job_gid: "5057"
                    job_gpus: "0"
                    job_id: "41504605"
                    job_name: asymetrictcontextlength_linearattention_test
                    job_nodelist: holygpu8a19301
                    job_num_nodes: "1"
                    job_partition: kempner
                    job_qos: normal
                    job_start_time: "1760499005"
                    job_uid: "64802"
                    job_user: mletey
                    jobid: "41504605"
                    localid: "0"
                    mem_per_gpu: "24576"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: holygpu8a19301
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    stepmgr: holygpu8a19301
                    submit_dir: /n/holystore01/LABS/pehlevan_lab/Lab/mletey/icl-bde/structured_linear_regression_icl
                    submit_host: holylogin07.rc.fas.harvard.edu
                    task_pid: "2413657"
                    tasks_per_node: "1"
                    topology_addr: main.holyoke.holyhdr.holygpu8a19301
                    topology_addr_pattern: switch.switch.switch.node
                startedAt: "2025-10-15T03:30:48.242195Z"
                writerId: e0z4hgxcti04n4dvt59n6th4o14vcamm
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 16
                - 61
            "4": 3.10.18
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
alpha:
    value: 1
amp:
    value: false
cpu:
    value: false
ctask:
    value: identity
d:
    value: 32
eval_every:
    value: 100
functionality:
    value: 1
grad_clip:
    value: 1
log_every:
    value: 25
lr:
    value: 0.001
project:
    value: linear-attn-demo
rho:
    value: 0.1
run_name:
    value: ""
seed:
    value: 0
steps:
    value: 2000
tau:
    value: 3
weight_decay:
    value: 0
